### ISSUE TITLE
When Read image it can't work properly

### ISSUE THREAD

**Issue by lanbao2021** [Hexmagic/ONNX-yolov5#1]
<img width="676" alt="image" src="https://user-images.githubusercontent.com/77654725/150650066-33937cdf-1416-400b-ab93-bdab9f7c6d82.png">

I need help🤕

**Comment by Hexmagic** [comment]
> <img alt="image" width="676" src="https://user-images.githubusercontent.com/77654725/150650066-33937cdf-1416-400b-ab93-bdab9f7c6d82.png">
> 
> I need help🤕

Can you provide idane.jpg ?

**Comment by lanbao2021** [comment]
zidane.jpg comes from data/images in your repo🤕 @Hexmagic

**Comment by Hexmagic** [comment]
> zidane.jpg comes from data/images in your repoface_with_head_bandage @Hexmagic

```c++
//main.cpp
Config config = {0.25f, 0.45f, model_path, "data/coco.names", Size(640, 640),false};
```
turn true to false`(auto=False)` will works right

**Comment by lanbao2021** [comment]
> 

thanks！
