### ISSUE TITLE
ONNX-yolov5 works on Windows 10, but not only uBuntu (22.04)

### ISSUE THREAD

**Issue by chyphen7** [Hexmagic/ONNX-yolov5#12]
Hi,

Thanks for sharing your code.  I have a Pytorch models (*.pt) trained with custom data, and have them converted to onnx using export.py from Ultralytic's yolov5.  ONNX-yolov5 works on Windows 10 as expected.  Then have ONNX-yolov5 compiled and built on uBuntue 22.04 and ran it with the same onnx  models, but it output incorrect bounding boxes.  I am wondering if there is I have pt files converted to onnx files corrected.  When running export.py I have tried with or without --simplify as suggested from one of posts on the internet.   Can you suggest right tools for converting pt files to onnx files?   Thanks,

CC

**Comment by Hexmagic** [comment]
sorry,I am not expert on this. Is opencv is  same  version on windows and ubuntu?

**Comment by chyphen7** [comment]
Yes, the same version. I have also tried out various versions and got
similar errors.

**Comment by Hexmagic** [comment]
how about update you onnx module ,or try use python onnxruntime check it output

**Comment by chyphen7** [comment]
Thanks, I'll check it out.

**Comment by zoldaten** [comment]
`python export.py --weights yolov5s.pt --include onnx --opset 12`  should work
