### ISSUE TITLE
Unsupported ONNX opset version: 17

### ISSUE THREAD

**Issue by BayRanger** [Hexmagic/ONNX-yolov5#13]
Hi，
I was trying to generate YOLOV5 onnx model with 
`python export.py --weights yolov5s.pt --include  onnx`
But, it turns out to be 
`ONNX: export failure ❌ 0.0s: Unsupported ONNX opset version: 17
`
So why the onnx cannot be exported with the default opset version 17?

**Comment by BayRanger** [comment]
change opset_version to 11 in export,py could resolve this issue, but I am silll confused with why I have to change it.

**Comment by Hexmagic** [comment]
according to this issue[Update to ONNX opset 17 ](https://github.com/ultralytics/yolov5/pull/10522) try update your onnx modle with command
`pip install -U onnx`

**Comment by AbdelsalamHaa** [comment]
Hi all, I have the same issue. I have tried to update onnx package but the same issue still there. 
I tried with onnx 1.12.0 and 1.13.0 The same error still occurs with both versions. 
My torch is version 1.9 

Any idea how to fix that. Thanks

**Comment by Hexmagic** [comment]
how about update your torch and torchvision ,I got same issue with torch 1.9

**Comment by AbdelsalamHaa** [comment]
Hi @Hexmagic 
Yea after updating torch to the latest version everything worked fine. Also keeping version 1.9 also worked given that I had to change the  opset_version to 11.  Maybe it is needed to update the documentation 

Is there any impact when using  opset_version to 11 or  opset_version to 17?

**Comment by Hexmagic** [comment]
> Hi @Hexmagic Yea after updating torch to the latest version everything worked fine. Also keeping version 1.9 also worked given that I had to change the opset_version to 11. Maybe it is needed to update the documentation
> 
> Is there any impact when using opset_version to 11 or opset_version to 17?

I think opset_version 17 just support more operator than 11
