### ISSUE TITLE
failed build on raspberry pi aarch64 Raspbian - [SOLVED]

### ISSUE THREAD

**Issue by zoldaten** [Hexmagic/ONNX-yolov5#14]
1.
i have had a problem with building so have to change CMakeLists.txt to:
```
cmake_minimum_required(VERSION 3.0 )
project(app)
set(CMAKE_CXX_STANDARD 14)
set(CMAKE_CXX_STANDARD_REQUIRED True)
SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -pthread")
find_package(OpenCV REQUIRED)
include_directories(
    ${OpenCV_INCLUDE_DIRS}
    ${PROJECT_SOURCE_DIR}/include
)
add_executable(main main.cpp  src/detector.cpp src/loguru.cpp)
target_link_libraries(main  ${OpenCV_LIBS} ${CMAKE_DL_LIBS})
add_executable(test src/test.cpp)
target_link_libraries(test  ${OpenCV_LIBS} ${CMAKE_DL_LIBS})
```
2.
and when converting in original yolov5 dir:
`python export.py --weights yolov5s.pt --include onnx --opset 12`

after that should work:
./build/main yolov5s.onnx data/images/zidane.jpg
![Screenshot_1](https://github.com/Hexmagic/ONNX-yolov5/assets/29411817/a3d9e925-bd11-4cb4-99c1-dcb7c0d2083e)

**Comment by Hexmagic** [comment]
👍
