### ISSUE TITLE
there is no speed up in c++ ?

### ISSUE THREAD

**Issue by zoldaten** [Hexmagic/ONNX-yolov5#15]
i see inference time about 1,7 sec with yolov5 onnx using 
./build/main yolov5s.onnx data/images/bus.jpg
![Screenshot_2](https://github.com/Hexmagic/ONNX-yolov5/assets/29411817/3cec6b91-1527-4f2a-965d-e7cf266fa867)
almost the same inference  time (1,3 sec) i see with yolov5 onnx:
![Screenshot_3](https://github.com/Hexmagic/ONNX-yolov5/assets/29411817/43252aca-df59-4024-b070-18eeb9eab5a1)

there is no advantage ? or i missed something ?

**Comment by Hexmagic** [comment]
with only one image there maybe no advantage ,and detect.py inference time no contain model load and image read time
