### ISSUE TITLE
error

### ISSUE THREAD

**Issue by never-to-never** [Hexmagic/ONNX-yolov5#4]
![image](https://user-images.githubusercontent.com/27321035/158121800-5371e984-3fc6-491b-ad54-bb9fa915d34f.png)
Why do model loads always report errors?The model path has also been modified.

**Comment by Hexmagic** [comment]
`test.cpp` is a scratch script, you can change this to your local yolov5 model path。

**Comment by Hexmagic** [comment]
If you want read model path from cmd param, I have updated test.cpp , git  pull and rebuild test.
```
./build/test  /your-local-path/yolov5.onnx 
```
