### ISSUE TITLE
how to change device to gpu

### ISSUE THREAD

**Issue by river-sing** [Hexmagic/ONNX-yolov5#5]
Hi, I built the main.exe using one computer with RTX 3060, and I copied the debug main.exe, yolov5s.onnx, opencv_world455d.dll, coco.names, test.jpg to my laptop with GTX 950m.

I have built the main.exe successfully, and run the `main yolov5s.onnx test.jpg` successfully. However, I found it is using the CPU of my laptop, not the GPU, while I do have a GPU GTX 950m.

What am I missing?

**Comment by Hexmagic** [comment]
change detector.cpp line 14 and line 15 
```c++
this->model.setPreferableBackend(dnn::DNN_BACKEND_OPENCV);
this->model.setPreferableTarget(dnn::DNN_TARGET_CPU);
```
to
```
this->model.setPreferableBackend(dnn::DNN_BACKEND_CUDA);
this->model.setPreferableTarget(dnn::DNN_TARGET_CUDA);
```
with minimum batch data GPU even slower than CPU(small data copy to tensor is expensive)
