### ISSUE TITLE
Correct model input size

### ISSUE THREAD

**Issue by MarcoMustacchi** [Hexmagic/ONNX-yolov5#7]
Hi, 
I have a model trained with an input img size of 416 and a batch size of 16.
how should the code change in this case?
thank you
( I had the following error )
<img width="954" alt="lllllllll" src="https://user-images.githubusercontent.com/75217227/177974245-877f9904-a0e9-4c67-983f-0cb5df058956.PNG">

**Comment by Hexmagic** [comment]
batch 1 is OK?

**Comment by Hexmagic** [comment]
edit batch_size into 16 when convert pytorch model into onnx 
![https://github.com/ultralytics/yolov5/blob/master/export.py](https://user-images.githubusercontent.com/11594791/179890406-b7b5409a-03ec-44d8-889a-719c6865a957.png)
